### ISSUE TITLE
Wrong calculation

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/isnack-paycheck#2]
This application isn't doing the right calculation.

![image](https://cloud.githubusercontent.com/assets/5324414/10761605/4e32ca0c-7ca9-11e5-8395-f130f32e21a4.png)

**Comment by isnack** [comment]
https://github.com/univas-first-exam/isnack-paycheck/blob/master/js/salaryServices.js#L10

O erro era causado por essa linha que não tinha antes fiquei acho que umas meia hora para achar,
se você for ver essa linha não está indentada mas tentei comitar novamente indentado mas não foi.

**Comment by edysegura** [comment]
No problem!!
